### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by bonesoul** [pietrasiak/jquery.initialize#12]
would be great if we could have a bower package :)

**Comment by DannyvanHolten** [comment]
Can I offer any help?

**Comment by pietrasiak** [comment]
@DannyvanHolten would be cool ;)

**Comment by DannyvanHolten** [comment]
I think I'll have time to look info it next week :) will send in a pull request

**Comment by dapicester** [comment]
See my PR #15

**Comment by pietrasiak** [comment]
merged ;)

**Comment by dapicester** [comment]
Thanks! I guess you can also close this issue.

**Comment by brspurri** [comment]
how would I use this from bower? `bower install jquery-initialize` comes back with `ENOTFOUND Package jquery-initialize not found`

**Comment by dapicester** [comment]
@brspurri I have the `"jquery-initialize": "pietrasiak/jquery.initialize"` entry in my `bower.json`.
