### ISSUE TITLE
initialize stops working after slider loops

### ISSUE THREAD

**Issue by ineedholidays** [pietrasiak/jquery.initialize#16]
Hi, 
I'm using initialize on lightslider this way:

```
$.initialize(".white-text.lslide.active", function() {
	$("#about").css("color", "white");
});
$.initialize(".black-text.lslide.active", function() {
	$("#about").css("color", "black");
});
```
It works perfectly, but if I go back on the slider or go through all slides, it will stop working. Any tips?

**Comment by dbezborodovrp** [comment]
I presume you are expecting the initialise function to be called every time the .active class is added?
 However, initialise will only be called once per element (when it is added to the DOM.)

**Comment by pietrasiak** [comment]
Yup. Initialize action is called once per DOM element. For sliding callback you should look for some hook to do that within slider plugin you use.
